---
- name: get temp directory
  shell: >
    /mnt/c/Windows/System32/cmd.exe /C "echo %TEMP%"
  register: multipass_create_temp_directory
  changed_when: false
  delegate_to: 127.0.0.1

- name: store temp directory
  set_fact:
    multipass_temp_directory: "{{ multipass_create_temp_directory.stdout_lines[0] }}"
  delegate_to: 127.0.0.1

- name: get temp directory for WSL
  shell: >
    wslpath $(/mnt/c/Windows/System32/cmd.exe /C "echo %TEMP%")
  register: multipass_create_temp_directory_wsl
  changed_when: false
  delegate_to: 127.0.0.1

- name: store temp directory for WSL
  set_fact:
    multipass_temp_directory_wsl: "{{ multipass_create_temp_directory_wsl.stdout_lines[0] }}"
  delegate_to: 127.0.0.1

- name: detect WSL
  set_fact:
    multipass_executable: "/mnt/c/Program Files/Multipass/bin/multipass.exe"
  delegate_to: 127.0.0.1
