---
- name: get directory for Windows
  shell: >
    wslpath -w {{ multipass_temp_directory_wsl }}
  register: multipass_create_temp_directory
  changed_when: false
  delegate_to: 127.0.0.1

- name: store directory for Windows
  set_fact:
    multipass_temp_directory: "{{ multipass_create_temp_directory.stdout_lines[0] }}"
  delegate_to: 127.0.0.1

- name: detect WSL
  set_fact:
    multipass_executable: "/mnt/c/Program Files/Multipass/bin/multipass.exe"
  delegate_to: 127.0.0.1
